http:
  routers:
    # n8n router
    n8n:
      rule: "Host(`n8n.myapp`)"
      entryPoints:
        - websecure
      service: n8n-service
      middlewares:
        - security-headers
      tls: {}

  services:
    # n8n service
    n8n-service:
      loadBalancer:
        servers:
          - url: "http://n8n:5678"
