api:
  dashboard: true
  insecure: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

providers:
  # File provider for static configuration
  file:
    directory: /etc/traefik/dynamic
    watch: true

tls:
  certificates:
    - certFile: /certs/react.myapp+1.pem
    - keyFile: /certs/react.myapp+1-key.pem
