services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - monitoring-networks

  mongodb-exporter:
    image: percona/mongodb_exporter:0.39
    ports:
      - 9216:9216
    environment:
      - MONGODB_URI=mongodb://root:example@mongodb:27017/admin
    depends_on:
      - mongodb
    networks:
      - monitoring-networks

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpressuser
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass
    networks:
      - monitoring-networks
